; PlatformIO Project Configuration File

[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_port = COM4
monitor_port = COM4
lib_deps =
  bblanchon/ArduinoJson @ ^7.4.3
  adafruit/Adafruit ADS1X15 @ ^2.5.0
  robtillaart/PCF8574 @ ^0.4.1

; If your hardware is a raw ESP-12E module instead of NodeMCU, use:
; [env:esp12e]
; platform = espressif8266
; board = esp12e
; framework = arduino
; monitor_speed = 115200
; lib_deps =
;   bblanchon/ArduinoJson @ ^7.4.3
