"""first db

Revision ID: 64dc5fdb3d0a
Revises: 
Create Date: 2026-04-27 03:34:54.153424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64dc5fdb3d0a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_targets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('disabled_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_targets_display_name'), 'face_targets', ['display_name'], unique=False)
    op.create_index(op.f('ix_face_targets_status'), 'face_targets', ['status'], unique=False)
    op.create_table('media_assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('secure_url', sa.String(length=1024), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('folder', sa.String(length=255), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('bytes', sa.Integer(), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_assets_created_at'), 'media_assets', ['created_at'], unique=False)
    op.create_index(op.f('ix_media_assets_public_id'), 'media_assets', ['public_id'], unique=False)
    op.create_index(op.f('ix_media_assets_purpose'), 'media_assets', ['purpose'], unique=False)
    op.create_table('model_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('model_type', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('model_path', sa.String(length=1024), nullable=False),
    sa.Column('labels_path', sa.String(length=1024), nullable=True),
    sa.Column('metrics_path', sa.String(length=1024), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_model_type'), 'model_versions', ['model_type'], unique=False)
    op.create_index(op.f('ix_model_versions_status'), 'model_versions', ['status'], unique=False)
    op.create_table('system_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('message', sa.String(length=1024), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_events_event_type'), 'system_events', ['event_type'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_name', sa.String(length=100), nullable=False),
    sa.Column('map_id', sa.String(length=50), nullable=False),
    sa.Column('segment_id', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('start_node', sa.String(length=20), nullable=False),
    sa.Column('target_node', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('record_camera', sa.Boolean(), nullable=False),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('output_dataset_path', sa.String(length=1024), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('stopped_at', sa.DateTime(), nullable=True),
    sa.Column('exported_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_created_at'), 'training_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_sessions_direction'), 'training_sessions', ['direction'], unique=False)
    op.create_index(op.f('ix_training_sessions_segment_id'), 'training_sessions', ['segment_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_session_name'), 'training_sessions', ['session_name'], unique=False)
    op.create_index(op.f('ix_training_sessions_status'), 'training_sessions', ['status'], unique=False)
    op.create_table('detection_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('target_person_id', sa.Uuid(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detected_node', sa.String(length=20), nullable=True),
    sa.Column('detected_segment_id', sa.String(length=50), nullable=True),
    sa.Column('snapshot_asset_id', sa.Uuid(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['target_person_id'], ['face_targets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detection_events_created_at'), 'detection_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_detection_events_detected_segment_id'), 'detection_events', ['detected_segment_id'], unique=False)
    op.create_index(op.f('ix_detection_events_event_type'), 'detection_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_detection_events_source'), 'detection_events', ['source'], unique=False)
    op.create_index(op.f('ix_detection_events_target_person_id'), 'detection_events', ['target_person_id'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('dimension', sa.Integer(), nullable=True),
    sa.Column('embedding_json', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_id'], ['face_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_target_id'), 'face_embeddings', ['target_id'], unique=False)
    op.create_table('face_target_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['face_targets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_target_images_media_asset_id'), 'face_target_images', ['media_asset_id'], unique=False)
    op.create_index(op.f('ix_face_target_images_target_id'), 'face_target_images', ['target_id'], unique=False)
    op.create_table('training_samples',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('media_asset_id', sa.Uuid(), nullable=True),
    sa.Column('timestamp_ms', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.String(length=50), nullable=False),
    sa.Column('direction', sa.String(length=50), nullable=False),
    sa.Column('current_node', sa.String(length=20), nullable=True),
    sa.Column('current_segment_id', sa.String(length=50), nullable=True),
    sa.Column('target_node', sa.String(length=20), nullable=True),
    sa.Column('joystick_x', sa.Integer(), nullable=True),
    sa.Column('joystick_y', sa.Integer(), nullable=True),
    sa.Column('left_motor_speed', sa.Integer(), nullable=True),
    sa.Column('right_motor_speed', sa.Integer(), nullable=True),
    sa.Column('front_distance_cm', sa.Float(), nullable=True),
    sa.Column('left_distance_cm', sa.Float(), nullable=True),
    sa.Column('right_distance_cm', sa.Float(), nullable=True),
    sa.Column('rear_distance_cm', sa.Float(), nullable=True),
    sa.Column('forward_unsafe', sa.Boolean(), nullable=True),
    sa.Column('object_found', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_asset_id'], ['media_assets.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_samples_created_at'), 'training_samples', ['created_at'], unique=False)
    op.create_index(op.f('ix_training_samples_session_id'), 'training_samples', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_samples_session_id'), table_name='training_samples')
    op.drop_index(op.f('ix_training_samples_created_at'), table_name='training_samples')
    op.drop_table('training_samples')
    op.drop_index(op.f('ix_face_target_images_target_id'), table_name='face_target_images')
    op.drop_index(op.f('ix_face_target_images_media_asset_id'), table_name='face_target_images')
    op.drop_table('face_target_images')
    op.drop_index(op.f('ix_face_embeddings_target_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index(op.f('ix_detection_events_target_person_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_source'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_event_type'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_detected_segment_id'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_created_at'), table_name='detection_events')
    op.drop_table('detection_events')
    op.drop_index(op.f('ix_training_sessions_status'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_session_name'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_segment_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_direction'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_created_at'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_system_events_event_type'), table_name='system_events')
    op.drop_table('system_events')
    op.drop_index(op.f('ix_model_versions_status'), table_name='model_versions')
    op.drop_index(op.f('ix_model_versions_model_type'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_media_assets_purpose'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_public_id'), table_name='media_assets')
    op.drop_index(op.f('ix_media_assets_created_at'), table_name='media_assets')
    op.drop_table('media_assets')
    op.drop_index(op.f('ix_face_targets_status'), table_name='face_targets')
    op.drop_index(op.f('ix_face_targets_display_name'), table_name='face_targets')
    op.drop_table('face_targets')
    # ### end Alembic commands ###
